[versions]
kotlinVer = "2.2.21"

junitVer = "6.0.1"
mockkVer = "1.14.6"
kotestVer = "6.1.0"
jimfsVer = "1.3.1"

deltaCoverageVer = "3.5.1"
detektVer = "1.23.8"

[libraries]
# Kotlin
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVer" }

# Plugins
pluginPublish = { module = "com.gradle.publish:plugin-publish-plugin", version = "2.0.0" }
deltaCoverage = { module = "io.github.gw-kit:delta-coverage-gradle", version.ref = "deltaCoverageVer" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektVer" }

# Testing
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVer" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVer" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotestVer" }
jimFs = { module = "com.google.jimfs:jimfs", version.ref = "jimfsVer" }

# Kotlin
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVer" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVer" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
deltaCoverage = { id = "io.github.gw-kit.delta-coverage", version.ref = "deltaCoverageVer" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVer" }
